////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// MIDTReadScaler                                                             //
//                                                                            //
// Begin_Html <!--
/*-->

<!--*/
// --> End_Html
//                                                                            //
//                                                                            //
// Please note: The following information is only correct after executing     //
// the ROMEBuilder.                                                           //
//                                                                            //
// This task accesses the following folders :                                 //
//     Scaler                                                                 //
//                                                                            //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

/* Generated header file containing necessary includes                        */
#include "generated/MIDTReadScalerGeneratedIncludes.h"

////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "generated/MIDAnalyzer.h"
#include "tasks/MIDTReadScaler.h"
#include "ROMEiostream.h"

// uncomment if you want to include headers of all folders
//#include "MIDAllFolders.h"


ClassImp(MIDTReadScaler)

using namespace std;

//______________________________________________________________________________
void MIDTReadScaler::Init()
{
}

//______________________________________________________________________________
void MIDTReadScaler::BeginOfRun()
{
}

//______________________________________________________________________________
void MIDTReadScaler::Event()
{
   cout << "SCLR" << endl;
   gAnalyzer->GetScaler()->SetcountSize(gAnalyzer->GetMidasDAQ()->GetSCLRBankEntries());
   Int_t i;
   for (i=0;i<gAnalyzer->GetMidasDAQ()->GetSCLRBankEntries();i++) {
      cout << i <<" "<<gAnalyzer->GetMidasDAQ()->GetSCLRBankAt(i) << endl;
      gAnalyzer->GetScaler()->SetcountAt(i, gAnalyzer->GetMidasDAQ()->GetSCLRBankAt(i));
   }

   // Need to set for non-trigger (EventID != 1) events
   gAnalyzer->SetFillEvent(kTRUE);

   cout << endl;
}

//______________________________________________________________________________
void MIDTReadScaler::EndOfRun()
{
}

//______________________________________________________________________________
void MIDTReadScaler::Terminate()
{
}

