////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// MIDTFillHistogram                                                          //
//                                                                            //
// Begin_Html <!--
/*-->

<!--*/
// --> End_Html
//                                                                            //
//                                                                            //
// Please note: The following information is only correct after executing     //
// the ROMEBuilder.                                                           //
//                                                                            //
//                                                                            //
// This task contains the following histgrams :                               //
//    ADC                                                                     //
//                                                                            //
// The histograms/graph are created and saved automaticaly by the task.       //
//                                                                            //
// The following method can be used to get a handle of the histogram/graph :  //
//                                                                            //
// Get<Histogram/Graph Name>()                                                //
//                                                                            //
// For histogram/graph arrays use :                                           //
//                                                                            //
// Get<Histogram/Graph Name>At(Int_t index)                                   //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

/* Generated header file containing necessary includes                        */
#include "generated/MIDTFillHistogramGeneratedIncludes.h"

////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "generated/MIDAnalyzer.h"
#include "tasks/MIDTFillHistogram.h"
#include "ROMEiostream.h"

// uncomment if you want to include headers of all folders
//#include "MIDAllFolders.h"


ClassImp(MIDTFillHistogram)

//______________________________________________________________________________
void MIDTFillHistogram::Init()
{
}

//______________________________________________________________________________
void MIDTFillHistogram::BeginOfRun()
{
}

//______________________________________________________________________________
void MIDTFillHistogram::Event()
{
   if (IsADCActive()) {
      for (Int_t i = 0; i < gAnalyzer->GetMidasDAQ()->GetADC0BankEntries(); i++) {
         if (i < 8) {
            GetADCAt(i)->Fill(gAnalyzer->GetMidasDAQ()->GetADC0BankAt(i));
         }
      }
   }
}

//______________________________________________________________________________
void MIDTFillHistogram::EndOfRun()
{
}

//______________________________________________________________________________
void MIDTFillHistogram::Terminate()
{
}

