// Author: Ryu Sawada <http://www.icepp.s.u-tokyo.ac.jp/%7Esawada>

#ifndef TMTT3_H
#define TMTT3_H

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
// TMTT3                                                                      //
//                                                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

////////////////////////////////////////////////////////////////////////////////
/*  This header was generated by ROMEBuilder. Manual changes above the        *
 * following line will be lost next time ROMEBuilder is executed.             */
/////////////////////////////////////----///////////////////////////////////////

#include "generated/TMTT3_Base.h"

class TMWindow;


class TMTT3 : public TMTT3_Base
{
protected:
   TGVerticalFrame     *fVert;
   TRootEmbeddedCanvas *fCanvas;

private:
   TMTT3(const TMTT3 &c); // not implemented
   TMTT3 &operator=(const TMTT3 &c); // not implemented

public:
   TMTT3(TMWindow* window = 0):TMTT3_Base(window)
   ,fVert(0)
   ,fCanvas(0)
   {
   }

   virtual ~TMTT3()
   {
      delete fVert;
      delete fCanvas;
   }

   void Init();
   void EndInit();
   void MenuClicked(TGPopupMenu *menu,Long_t param);
   void TabSelected();
   void TabUnSelected();
   void EventHandler();

protected:
   void OpenPad(Int_t id);

   ClassDef(TMTT3,1)
};

#endif   // TMTT3_H
